### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by MikeBeller** [ToucanProtocol/contracts#3]
Currently, the internal links in README.md are broken.  In particular, I am trying to build the contracts from this repo, and the links which purport to  explain how to do this are "not found" because the target files are not in the documentation folder.  

Example from the raw README source:

```
- [Our security model and processes](documentation/security.md)
- [How to set up your local workstation](documentation/local-setup.md)
...
```

These and the following links are broken.

**Comment by mayassalman** [comment]
Same for me

**Comment by 0xmichalis** [comment]
These dead links are removed now, hopefully we can start introducing some of the linked docs as part of this repo in the future.
